### PR TITLE
[twitter] Migrate panel to Kibana 6

### PR DESCRIPTION
**Pull request by alpgarcia**

### CODE REVIEW

**Comment by dicortazar** [comment]
Hi @alpgarcia, thanks for the PR.

I was wondering if we can use the tag cloud viz for the hashtags and then we could resize the two top right charts (Organizations and Main Hashtags) and have the three visualizations there.

**Comment by alpgarcia** [comment]
We could add a tag cloud, but if we remove the current table we are missing info related to those tags.

**Comment by dicortazar** [comment]
@alpgarcia I'm afraid I do not see any tag cloud in the panel yet.

**Comment by dicortazar** [comment]
LGTM, thanks!

**Pull request closed without merging**
