### PR TITLE
[mediawiki] Use 'edits' instead of 'editions'

### PR DESCRIPTION
**Pull request by alpgarcia**

### CODE REVIEW

**Comment by alpgarcia** [comment]
This is related to #232

**Comment by alpgarcia** [comment]
Substituted also in page titles.

Besides, word 'last' has been changed by 'latest' which meaning is more accurate imho.

**Comment by dicortazar** [comment]
Great, thanks a lot for the update.

**Comment by dicortazar** [comment]
Already merged.

**Pull request closed without merging**
