### PR TITLE
[git-demographics] Change title `git_demographics_people_leaving_community`

### PR DESCRIPTION
**Pull request by RCheesley**
The title of the visualization `git_demographics_people_leaving_community` has been modified from `Developers getting Inactive` to `Developers Becoming Inactive`

Signed-off-by: Ruth Cheesley <ruth.cheesley@acquia.com>

### CODE REVIEW

**Comment by valeriocos** [comment]
Thank you @RCheesley for the PR and sorry for the late reply!

**Comment by valeriocos** [comment]
@alpgarcia, feel free to have a look at the PR in the next days (when you are back from vacations)? thanks

captura_113

**Comment by GeorgLink** [comment]
I agree with the name change of the visualization. Thanks @RCheesley

**Comment by RCheesley** [comment]
I think it might appear elsewhere in the dashboard, I tried to look but got
distracted! :)

Ruth

Ruth Cheesley

ACQUIA

Mautic Community Manager

p: +44 (0)1442 734282 | m: +44 (0) 7308 164475 | e: ruth.cheesley@acquia.com

/ WE ARE THE OPEN SOURCE DIGITAL EXPERIENCE COMPANY.
<https://www.acquia.com/>

**Comment by valeriocos** [comment]
thank you for the info @RCheesley , I'll check and update the PR

**Comment by valeriocos** [comment]
@RCheesley I have incapsulated your PR to this one: https://github.com/chaoss/grimoirelab-sigils/pull/389. Hope this is fine for you

**Comment by RCheesley** [comment]
Perfect! Thank you!

Ruth Cheesley

ACQUIA

Mautic Community Manager

p: +44 (0)1442 734282 | m: +44 (0) 7308 164475 | e: ruth.cheesley@acquia.com

/ WE ARE THE OPEN SOURCE DIGITAL EXPERIENCE COMPANY.
<https://www.acquia.com/>

**Comment by valeriocos** [comment]
thank you @RCheesley for the contribution and thank you @GeorgLink for the support.

**Pull request closed without merging**
