### PR TITLE
Efficiency panel for GitLab Issues

### PR DESCRIPTION
**Pull request by mafesan**
Following the guidelines from https://github.com/chaoss/grimoirelab-sigils/issues/302, here is the panel for measuring efficiency closing GitLab Issues.

In this PR I'm including:
* Exported panel (JSON file).
* Documentation: Markdown document + screenshot (PNG format).

### CODE REVIEW

**Comment by mafesan** [comment]
Thank you @alpgarcia for your comments. I have applied the changes you requested, now you can see the repositories as hyperlinks. However, you will notice that the repo appears with the full URL instead of the shortened version of the repo name (i.e., `https://gitlab.com/gitlab-org/gitlab-ce` instead of `gitlab-org/gitlab-ce`), as now it is being used the field `repository`, which is the most suitable one that I found.

I have also updated the screenshot for the documentation.

**Comment by alpgarcia** [comment]
As I said in the issue, please update panel taking into account #314.

**Comment by mafesan** [comment]
Done @alpgarcia,

I have added the time unit and updated the screenshot, please proceed to review these changes.

**Comment by mafesan** [comment]
@alpgarcia I have added the time unit in `Lead Time` visualization legend, so the changes you requested should be complete now. Please, review it.

**Comment by alpgarcia** [comment]
LGTM, thanks!

**Pull request closed without merging**
