### PR TITLE
[jira] Update panels to new index structure

### PR DESCRIPTION
**Pull request by alpgarcia**
This commit updates Jira panels to support changes added by
chaoss/grimoirelab-elk#656.

This should solve #378

Signed-off-by: Alberto Pérez García-Plaza <alpgarcia@bitergia.com>

### CODE REVIEW

**Comment by alpgarcia** [comment]
Last commit also updates `affiliations` index pattern to include the new Jira fields.

**Comment by sduenas** [comment]
I've got this error when testing these panels. I found it in `Jira Timing` panel.

```
Error: Request to Elasticsearch failed: {"error":{"root_cause":[{"type":"query_shard_exception","reason":"No mapping found for [resolution_date] in order to sort on","index_uuid":"tnu6oWQlSaOkTZRjPQN0kg","index":"jira_enriched"}],"type":"search_phase_execution_exception","reason":"all shards failed","phase":"query","grouped":true,"failed_shards":[{"shard":0,"index":"jira_enriched","node":"Ny5m9PhUSSmlAuAzde80qA","reason":{"type":"query_shard_exception","reason":"No mapping found for [resolution_date] in order to sort on","index_uuid":"tnu6oWQlSaOkTZRjPQN0kg","index":"jira_enriched"}}]},"status":400}
KbnError@http://127.0.0.1:5601/bundles/commons.bundle.js?v=1:1:9151
RequestFailure@http://127.0.0.1:5601/bundles/commons.bundle.js?v=1:1:9948
callResponseHandlers/<@http://127.0.0.1:5601/bundles/kibana.bundle.js?v=1:61:650116
Promise.try@http://127.0.0.1:5601/bundles/commons.bundle.js?v=1:56:19076
Promise.map/<@http://127.0.0.1:5601/bundles/commons.bundle.js?v=1:56:18461
Promise.map@http://127.0.0.1:5601/bundles/commons.bundle.js?v=1:56:18422
callResponseHandlers@http://127.0.0.1:5601/bundles/kibana.bundle.js?v=1:61:649694
fetchSearchResults/<@http://127.0.0.1:5601/bundles/kibana.bundle.js?v=1:61:639054
processQueue@http://127.0.0.1:5601/bundles/commons.bundle.js?v=1:35:132456
scheduleProcessQueue/<@http://127.0.0.1:5601/bundles/commons.bundle.js?v=1:35:133349
$digest@http://127.0.0.1:5601/bundles/commons.bundle.js?v=1:35:144239
$apply@http://127.0.0.1:5601/bundles/commons.bundle.js?v=1:35:147018
done@http://127.0.0.1:5601/bundles/commons.bundle.js?v=1:35:100026
completeRequest@http://127.0.0.1:5601/bundles/commons.bundle.js?v=1:35:104697
createHttpBackend/</xhr.onload@http://127.0.0.1:5601/bundles/commons.bundle.js?v=1:35:105435
```

**Comment by alpgarcia** [comment]
> I've got this error when testing these panels. I found it in `Jira Timing` panel.
> 
> ```
> Visualize: No mapping found for [resolution_date] in order to sort on
> 
> Error: Request to Elasticsearch failed: {"error":{"root_cause":[{"type":"query_shard_exception","reason":"No mapping found for [resolution_date] in order to sort on","index_uuid":"tnu6oWQlSaOkTZRjPQN0kg","index":"jira_enriched"}],"type":"search_phase_execution_exception","reason":"all shards failed","phase":"query","grouped":true,"failed_shards":[{"shard":0,"index":"jira_enriched","node":"Ny5m9PhUSSmlAuAzde80qA","reason":{"type":"query_shard_exception","reason":"No mapping found for [resolution_date] in order to sort on","index_uuid":"tnu6oWQlSaOkTZRjPQN0kg","index":"jira_enriched"}}]},"status":400}
> KbnError@http://127.0.0.1:5601/bundles/commons.bundle.js?v=1:1:9151
> RequestFailure@http://127.0.0.1:5601/bundles/commons.bundle.js?v=1:1:9948
> callResponseHandlers/<@http://127.0.0.1:5601/bundles/kibana.bundle.js?v=1:61:650116
> Promise.try@http://127.0.0.1:5601/bundles/commons.bundle.js?v=1:56:19076
> Promise.map/<@http://127.0.0.1:5601/bundles/commons.bundle.js?v=1:56:18461
> Promise.map@http://127.0.0.1:5601/bundles/commons.bundle.js?v=1:56:18422
> callResponseHandlers@http://127.0.0.1:5601/bundles/kibana.bundle.js?v=1:61:649694
> fetchSearchResults/<@http://127.0.0.1:5601/bundles/kibana.bundle.js?v=1:61:639054
> processQueue@http://127.0.0.1:5601/bundles/commons.bundle.js?v=1:35:132456
> scheduleProcessQueue/<@http://127.0.0.1:5601/bundles/commons.bundle.js?v=1:35:133349
> $digest@http://127.0.0.1:5601/bundles/commons.bundle.js?v=1:35:144239
> $apply@http://127.0.0.1:5601/bundles/commons.bundle.js?v=1:35:147018
> done@http://127.0.0.1:5601/bundles/commons.bundle.js?v=1:35:100026
> completeRequest@http://127.0.0.1:5601/bundles/commons.bundle.js?v=1:35:104697
> createHttpBackend/</xhr.onload@http://127.0.0.1:5601/bundles/commons.bundle.js?v=1:35:105435
> ```

You are probably using data from a source that don't use `resolution_date` field, so that the visualization based on closed issues can't work on top of these data. In those cases this visualization makes no sense and should be removed from the dashboard.

**Comment by sduenas** [comment]
> > I've got this error when testing these panels. I found it in `Jira Timing` panel.
> > ```
> > Visualize: No mapping found for [resolution_date] in order to sort on
> > 
> > Error: Request to Elasticsearch failed: {"error":{"root_cause":[{"type":"query_shard_exception","reason":"No mapping found for [resolution_date] in order to sort on","index_uuid":"tnu6oWQlSaOkTZRjPQN0kg","index":"jira_enriched"}],"type":"search_phase_execution_exception","reason":"all shards failed","phase":"query","grouped":true,"failed_shards":[{"shard":0,"index":"jira_enriched","node":"Ny5m9PhUSSmlAuAzde80qA","reason":{"type":"query_shard_exception","reason":"No mapping found for [resolution_date] in order to sort on","index_uuid":"tnu6oWQlSaOkTZRjPQN0kg","index":"jira_enriched"}}]},"status":400}
> > KbnError@http://127.0.0.1:5601/bundles/commons.bundle.js?v=1:1:9151
> > RequestFailure@http://127.0.0.1:5601/bundles/commons.bundle.js?v=1:1:9948
> > callResponseHandlers/<@http://127.0.0.1:5601/bundles/kibana.bundle.js?v=1:61:650116
> > Promise.try@http://127.0.0.1:5601/bundles/commons.bundle.js?v=1:56:19076
> > Promise.map/<@http://127.0.0.1:5601/bundles/commons.bundle.js?v=1:56:18461
> > Promise.map@http://127.0.0.1:5601/bundles/commons.bundle.js?v=1:56:18422
> > callResponseHandlers@http://127.0.0.1:5601/bundles/kibana.bundle.js?v=1:61:649694
> > fetchSearchResults/<@http://127.0.0.1:5601/bundles/kibana.bundle.js?v=1:61:639054
> > processQueue@http://127.0.0.1:5601/bundles/commons.bundle.js?v=1:35:132456
> > scheduleProcessQueue/<@http://127.0.0.1:5601/bundles/commons.bundle.js?v=1:35:133349
> > $digest@http://127.0.0.1:5601/bundles/commons.bundle.js?v=1:35:144239
> > $apply@http://127.0.0.1:5601/bundles/commons.bundle.js?v=1:35:147018
> > done@http://127.0.0.1:5601/bundles/commons.bundle.js?v=1:35:100026
> > completeRequest@http://127.0.0.1:5601/bundles/commons.bundle.js?v=1:35:104697
> > createHttpBackend/</xhr.onload@http://127.0.0.1:5601/bundles/commons.bundle.js?v=1:35:105435
> > ```
> 
> You are probably using data from a source that don't use `resolution_date` field, so that the visualization based on closed issues can't work on top of these data. In those cases this visualization makes no sense and should be removed from the dashboard.

Understood. That was the problem.

**Pull request closed without merging**
