### PR TITLE
Updated docker.json, replaced sirmordred repo link

### PR DESCRIPTION
**Pull request by abhiandthetruth**
Changed the specific reference to a sirmordred readme section in docker.json to generic repo reference.

Signed-off-by: abhiandthetruth <abhiandthetruth@gmail.com>
Linked To https://github.com/chaoss/grimoirelab-sirmordred/issues/433

### CODE REVIEW

**Comment by abhiandthetruth** [comment]
That's a good point. This will always lead to inconsistencies whenever the sirmordred documentation. We can change the specific reference to a generic reference i.e., to the repository itself which I think is not going to change. WDYT?

**Comment by valeriocos** [comment]
Yes, this is also a good option and probably better than the first one. Can you update the `release_date` attribute at https://github.com/chaoss/grimoirelab-sigils/blob/master/json/docker.json#L17 with the current date?

This change is needed to be able to differenciate between the different versions of a dashboard. Under the hood GrimoireLab uses this date to detect changes on the dashboard and perform automatic updates. 

The `release_date` is automatically set when exporting a dashboard using Kidash (https://github.com/chaoss/grimoirelab-sigils/blob/master/CONTRIBUTING.md#opening-a-new-pull-request), however I understand that this process may be cumbersome for a first-time contribution, and may be not needed in this specific case.

It would be great if you can follow the process below. If you find any problem, we can go for the easy way.

The ideal process should be:
- Upload the current dashboard to your Kibiter
- Made the change on the visualization
- Save the dashboard
- Export the dashboard with kidash (see https://github.com/chaoss/grimoirelab-sigils/blob/master/CONTRIBUTING.md#exporting-panel)
- Submit a PR with the new dashboard

Easy way:
- Change the `release_date` manually and update the PR :)

**Comment by abhiandthetruth** [comment]
I hope the easy way doesn't have side effects cause I'm opting for it ;)

**Comment by abhiandthetruth** [comment]
@valeriocos Done! Please review

**Comment by abhiandthetruth** [comment]
Done @valeriocos . Sorry for the commit message earlier.

**Pull request merged**
