### PR TITLE
[gitlab] Replace `gitlab` alias with `gitlab_issues`

### PR DESCRIPTION
**Pull request by valeriocos**
This code renames the index pattern for issues, thus the name is chagend from `gitlab` to `gitlab_issues`. Furthermore, it updates the timelion charts in the efficiency panel (which uses gitlab alias).

### CODE REVIEW

**Comment by alpgarcia** [comment]
Notice this needs https://github.com/chaoss/grimoirelab-sirmordred/pull/296

**Comment by alpgarcia** [comment]
Tested and working. I noticed two Timelion charts in `Efficiency` panel that uses `gitlab` alias (due to timelion uses expressions that are string literals).

@valcos could you please update those too and include the panel in this PR?

**Comment by valeriocos** [comment]
PR updated @alpgarcia , please recheck

**Comment by alpgarcia** [comment]
Thanks @valeriocos!! LGTM!

**Pull request closed without merging**
