### PR TITLE
Fix link to CSV schema directory and add JBC panel

### PR DESCRIPTION
**Pull request by jsmanrique**

### CODE REVIEW

**Comment by jsmanrique** [comment]
I don't know how to split this 2 commits in 2 different PRs

**Comment by dicortazar** [comment]
@jsmanrique thanks for this.

Would you mind updating the name of the panel to something more meaningful? We need an update in the panel name and in the file name.

For instance, as this is based on GitHub information, a title such as github_development_activity_summary may work.

Thanks!

**Comment by jsmanrique** [comment]
Let's close this pull request. I'll send a new one.

**Comment by jsmanrique** [comment]
This PR is now follow up in #311

**Pull request closed without merging**
