### PR TITLE
Efficiency panel for GitLab Merge Requests

### PR DESCRIPTION
**Pull request by mafesan**
Following the guidelines from https://github.com/chaoss/grimoirelab-sigils/issues/302, here is the panel for measuring efficiency solving GitLab Merge Requests.

In this PR I'm including:
* Exported panel (JSON file).
* Updated Index pattern.
* Documentation: Markdown document + screenshot (PNG format).

### CODE REVIEW

**Comment by alpgarcia** [comment]
As I said in the issue, please update panel taking into account #314.

**Comment by mafesan** [comment]
Done @alpgarcia, 

I have added the time unit and updated the screenshot, please proceed to review these changes.

**Comment by mafesan** [comment]
@alpgarcia I have added the time unit in Lead Time visualization legend, so the changes you requested should be complete now. Please, review it.

**Comment by alpgarcia** [comment]
LGTM, thanks!

**Pull request closed without merging**
