### PR TITLE
Restructure panels folders

### LINKED ISSUE #315: Update directories and file names to be more meaningful
First of all, is it a repository of one collection of panels, or several collections? It seems it's growing to several panels collections, isn't it?:
- `json` (current GrimoireLab _standard_ panels). These are the ones installed also through PyPi packages (see [panels](https://github.com/chaoss/grimoirelab-sigils/tree/master/panels) directory used in the package)
- `dashboards-cauldron`. The legacy panels used in [Cauldron.io](https://cauldron.io). They should be _deprecated_ at some point
- `chaoss-gmd-cde`. The upcoming [CHAOSS GMD Code Development focus area](https://github.com/chaoss/wg-gmd/blob/master/focus_areas/code_development.md) panels

There are also code and tools related with panels management, that are stored here too:
- `import_panels.sh`
- `src` directory

So, my proposal would be:
- provide meaningful names to the `.json` panels files directories. I would recommend to avoid acronyms. So they could become:
  * rename `json` folder to `sigils`: standard set of GrimoireLab panels. It would be needed to rewrite the symbolic link in `panels` directory (or improve the way the package manages the panels collections), and maybe it could have some undesired effects in current Bitergia deployment infra (but that's Bitergia issue, not GrimoireLab Sigils issue).
  * rename `dashboards-cauldron` to `cauldron`: set of panels used in [Cauldron.io](https://cauldron.io)
  * rename `chaoss-gmd-cde` to `chaoss-gmd-wg-code-development`
- move the tools and scrips to a `utils` directory, with its own README.md or set of `.md` files for documentation
- use `docs` folder for GrimoireLab Sigils and its collections documentation. This mean, that there could be several docs or pages in that folder, and a set of collections with the same names that the ones used in the root directory for the directories of `.json` files.

### PR DESCRIPTION
**Pull request by jsmanrique**
This PR should fix #315

### CODE REVIEW

**Comment by alpgarcia** [comment]
I think we need @jgbarah and @valeriocos help here to ensure we are aware of the implications of modifying directory names may have in pip packages and sirmordred. 

Could you please comment the requirements we must take into account when renaming sigils directories?

**Comment by alpgarcia** [comment]
Please @valeriocos, @jgbarah we are waiting for your comments here.

**Comment by valeriocos** [comment]
I'm not sure I should have been mentioned since I'm not really involved in the packaging of GrimoireLab.

The connection between Sigils and the platform is here: https://github.com/chaoss/grimoirelab-kidash/blob/master/kidash/kidash.py#L681, so as long as you don't change the location/names of `panels/json` and `json`, everything should work fine. If you plan to rename these folders, be sure that the changes are consistent with the attributes `packages` and `package_data` (https://github.com/chaoss/grimoirelab-sigils/blob/master/setup.py#L69).

In order to the test this PR, I did the following:
- checkout the branch of this PR
- execute micro mordred with option `--panels`
- check that no error message was thrown

Hope this helps

**Comment by alpgarcia** [comment]
Thanks @valcos!

@jgbarah, @sduenas something to add here?

**Comment by dicortazar** [comment]
Is there anything I can do to move this forward?

**Comment by alpgarcia** [comment]
@jsmanrique I fear this is not valid anymore. Should we close it?

**Comment by alpgarcia** [comment]
Closing as won't fix ... yet.

**Pull request closed without merging**
