### PR TITLE
[maniphest] Change `painless_delay` instead of `timeopen_days`

### PR DESCRIPTION
**Pull request by zhquan**
`painless_delay` (scripted field):
- If the ticket is close is the same as `time_to_close_days`.
- If the ticket is still open diff between `creaton_date` and now.

The field `timeopen_days` is removed from elk.

The documentation related to maniphest-timing is added.

More info at https://github.com/chaoss/grimoirelab-elk/issues/910

Signed-off-by: Quan Zhou <quan@bitergia.com>

### CODE REVIEW

**Comment by sanacl** [comment]
Question folks @alpgarcia @zhquan . I see this was closed but not merged. You are aware of this right?

**Comment by zhquan** [comment]
@sanacl this is merged https://github.com/chaoss/grimoirelab-sigils/commit/723ab1bf0492490155c8c9c91aa44ec30fa20834

**Comment by alpgarcia** [comment]
@sanacl this is because I rebased the branch to keep everything sorted (from the command line). In those cases, GitHub doesn't know I'm merging and just marks the PR as closed.

But, if you look at the history you can find the line in which the PR is closed and it contains the merge commit:
```
alpgarcia closed this in 723ab1b 2 days ago
```

**Comment by sanacl** [comment]
crystal clear, thank u @alpgarcia :+1:

**Pull request closed without merging**
