### PR TITLE
Update graal panels

### PR DESCRIPTION
**Pull request by valeriocos**
This PR updates the panels for cocom and colic to prevent the use of the field `origin` in different tables. This change is needed to avoid exposing tokens or other credentials passed in the `origin`.

The visualizations in the dashboard Cocom with titles "Repositories" and the "All Files: Code complexity, LOC and ratios" have been updated and now use the field `repo_url` (which doesn't expose credentials) instead of `origin`. Similar thing has been done for the visualizations with titles "Repositories" and "All Files: License & Copyright Definition" in the Colic dashboard.

Note that the origin and the credentials can be visualized by inspecting the raw or/and enriched index.

Related issues/prs:
- https://github.com/chaoss/grimoirelab-elk/issues/759
- https://github.com/chaoss/grimoirelab-elk/pull/763

### CODE REVIEW

**Comment by alpgarcia** [comment]
@sduenas these dashboards are already documented:
* https://chaoss.github.io/grimoirelab-sigils/panels/cocom/
* https://chaoss.github.io/grimoirelab-sigils/panels/colic/

Not sure if you refer to adding a markdown widget with basic information and a link to these documents from the dashboards.

**Comment by sduenas** [comment]
> @sduenas these dashboards are already documented:
> 
>     * https://chaoss.github.io/grimoirelab-sigils/panels/cocom/
> 
>     * https://chaoss.github.io/grimoirelab-sigils/panels/colic/
> 
> 
> Not sure if you refer to adding a markdown widget with basic information and a link to these documents from the dashboards.

My mystake. I thought this was the first time these panels were added to the repository.

**Comment by valeriocos** [comment]
@sduenas I have updated the commit message, please let me know if the purpose of the PR isn't clear

**Comment by sduenas** [comment]
That's more clear, yes.

**Pull request merged**
